name: Build, Test & Benchmark main

on:
  push:
    branches:
      - main
      - fixactions
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  buildTest:
    permissions:
      contents: write
    name: Build, Test & Benchmark code
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ">=3.12.0"

      - name: Install cavro
        run: pip install .[test]

      - name: Run tests
        run: env PYTHONPATH=. pytest

      - name: Install benchmark requirements
        run: pip install -r benchmark/requirements.txt

      - name: Download historic benchmark data
        run: |
          curl -L https://raw.githubusercontent.com/cavro-py/cavro/perf/perf_results.json > perf_results.json

      - name: Run Benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: PYTHONPATH=. python3 benchmark/main.py --output perf_results.json -h ${{ github.sha }}

      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const branch = 'perf';
            const ref = branch;
            const path = 'perf_results.json';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = (await github.rest.repos.getContent({owner, repo, path, ref})).data.sha;

            const content = fs.readFileSync('perf_results.json').toString('base64');
            const message = 'Update perf_results.json from GitHub Actions';

            await github.rest.repos.createOrUpdateFileContents({
              owner, repo, path, branch, sha, content, message
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Python requirements
        run: pip install pdoc jupyterlab

      - name: Autogenerate docs pages
        run: ./mkdocs.sh

      - uses: actions/setup-node@v3
        
      - name: Install docs requirements
        run: cd doc && npm install

      - name: Build docs
        run: cd doc && npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: doc/build
