on: [push, pull_request]
name: Build&Test
jobs:
  buildTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker
        run: docker build -t stestagg/cavro .
      - name: Test image
        run: docker run --rm stestagg/cavro -c 'PYTHONPATH=. pytest'
