on: [push, pull_request]
name: Build&Test
jobs:
  buildTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build & Test
        uses: actions/docker/cli@master
        with:
          args: build -t stestagg/cavro .
