on:
  push:
    branches:
      - main
      - fixactions
name: Build&Benchmark
jobs:
  buildBenchmark:
    name: Build, Test & Benchmark code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Fetch refs
        run: git fetch -v origin +refs/perf/\*:refs/perf/\*
      - name: Install cavro
        run: pip install .[test]
      - name: Install benchmark requirements
        run: pip install -r benchmark/requirements.txt
      - name: Run Benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: PYTHONPATH=. python3 benchmark/main.py
      - name: Upload updated results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: PYTHONPATH=. python3 benchmark/update_docs.py
 
