on:
  push:
    branches:
      - main
      - fixactions
name: Build&Benchmark
jobs:
  buildBenchmark:
    name: Build, Test & Benchmark code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Test image
        run: docker run --rm stestagg/cavro -c 'PYTHONPATH=. pytest'
      - name: Run Benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run -e GITHUB_TOKEN --rm stestagg/cavro -c 'PYTHONPATH=. python3 benchmark/main.py'
      - name: Upload updated results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: docker run -e GITHUB_TOKEN -e UPLOAD_TOKEN --rm stestagg/cavro -c 'make upload_benchmark_docker'
 
