name: TestPR

on:
  pull_request:
    
jobs:
  buildTest:
    name: Build, Test & Benchmark code
    runs-on: ubuntu-latest
    outputs:
      benchmark-output: ${{ steps.benchmark.outputs.BENCHMARK_OUTPUT }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install cavro
        run: pip install .[test]
      - name: Run tests
        run: env PYTHONPATH=. pytest
      - name: Install benchmark requirements
        run: pip install -r benchmark/requirements.txt
      - id: benchmark
        name: Run Benchmark
        run: |
          PYTHONPATH=. python3 benchmark/main.py > benchmark_output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark_output
          path: benchmark_output.txt
