name: TestPR

on:
  pull_request:
    
jobs:
  buildTest:
    name: Build, Test & Benchmark code
    runs-on: ubuntu-latest
    outputs:
      benchmark-output: ${{ steps.benchmark.outputs.BENCHMARK_OUTPUT }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install cavro
        run: pip install .[test]
      - name: Run tests
        run: env PYTHONPATH=. pytest
      - name: Install benchmark requirements
        run: pip install -r benchmark/requirements.txt
      - id: benchmark
        name: Run Benchmark
        run: |
          {
            echo 'BENCHMARK_OUTPUT<<EOF'
            PYTHONPATH=. python3 benchmark/main.py -x
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Benchmark Results: ${{ steps.benchmark.outputs.BENCHMARK_OUTPUT }}'
            })
